/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <cstdint>
#include <DataFlow/Table.hpp>
/* Header for class org_apache_hadoop_hive_ql_exec_ghive_JNIInterface */

#ifndef _Included_org_apache_hadoop_hive_ql_exec_ghive_JNIInterface
#define _Included_org_apache_hadoop_hive_ql_exec_ghive_JNIInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_hive_ql_exec_ghive_JNIInterface
 * Method:    GPUProcess
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_apache_hadoop_hive_ql_exec_ghive_JNIInterface_GPUProcess
  (JNIEnv *, jclass, jobject);

jobject generate_result(JNIEnv *env, long **long_cols, double **double_cols,int **int_cols,
                        char **str_cols, int **str_idx_cols,
                        const uint32_t long_col_num,
                        const uint32_t double_col_num,
                        const uint32_t int_col_num,
                        const uint32_t string_col_num,
                        const uint32_t row_cnt,
                        int *sequence);

jobject generate_tbl_result(JNIEnv *env, Table *result_tbl);

#ifdef __cplusplus
}
#endif
#endif
